spring.application.name=jobFlow

spring.datasource.url= jdbc:mysql://localhost:3306/jobflow
spring.datasource.username= root
spring.datasource.password= Melonete_2001

spring.jpa.hibernate.ddl-auto= validate
spring.jpa.show-sql= true
spring.jpa.properties.hibernate.format_sql= true
